import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import { 
  ShieldCheck, Award, CheckCircle, Search, Calendar, 
  Printer, Lock, BookOpen
} from 'lucide-react';
import './VerifyCertificate.css';

// Preloaded verified certificate ledger
const VERIFIED_RECORDS = {
  'EDU-2026-REACT-8842': {
    id: 'EDU-2026-REACT-8842',
    studentName: 'Jithendar Ramagiri',
    courseTitle: 'Advanced React 19 & Next.js 15 Patterns',
    category: 'Programming & Web Architecture',
    completionDate: 'February 18, 2026',
    grade: '98% (Distinction)',
    instructor: 'Dan Abramov & EduLearn Faculty',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    status: 'Verified & Tamper-Proof',
    skills: ['React 19 Server Actions', 'React Forget Compiler', 'Next.js 15 App Router', 'Concurrent Hydration', 'Zustand State']
  },
  'EDU-2026-AI-4910': {
    id: 'EDU-2026-AI-4910',
    studentName: 'Priya Sharma',
    courseTitle: 'Full-Stack Generative AI & Autonomous Agents',
    category: 'Artificial Intelligence',
    completionDate: 'January 12, 2026',
    grade: '95% (Distinction)',
    instructor: 'Andrej Karpathy & EduLearn AI Labs',
    sha256Hash: '7d793037a0760186574b0282f2f435e7b1e51a4c92f8b3e3d29654f494da9b7a',
    status: 'Verified & Tamper-Proof',
    skills: ['Transformers', 'RAG Architectures', 'LangChain', 'Vector Search', 'Multi-Agent Orchestration']
  },
  'EDU-2026-CLOUD-1738': {
    id: 'EDU-2026-CLOUD-1738',
    studentName: 'Alex Mercer',
    courseTitle: 'Docker & Production Kubernetes Mastery',
    category: 'Cloud & DevOps',
    completionDate: 'December 28, 2025',
    grade: '92% (Pass with Honors)',
    instructor: 'Kelsey Hightower',
    sha256Hash: 'a8b7c6d5e4f3a2b10987654321fedcba0123456789abcdef0123456789abcdef',
    status: 'Verified & Tamper-Proof',
    skills: ['Kubernetes Helm', 'Terraform Multi-Cloud', 'Docker Swarm', 'Observability', 'GitOps CI/CD']
  }
};

const VerifyCertificate = () => {
  const { id } = useParams();
  const [certInput, setCertInput] = useState(id || 'EDU-2026-REACT-8842');
  const [activeCert, setActiveCert] = useState(() => {
    return VERIFIED_RECORDS[id] || VERIFIED_RECORDS['EDU-2026-REACT-8842'];
  });
  const [searched, setSearched] = useState(true);

  const handleSearch = (e) => {
    e?.preventDefault();
    const cleanId = certInput.trim().toUpperCase();
    if (!cleanId) return;

    if (VERIFIED_RECORDS[cleanId]) {
      setActiveCert(VERIFIED_RECORDS[cleanId]);
    } else {
      // Dynamic on-the-fly verification for custom IDs generated by student certificates
      setActiveCert({
        id: cleanId,
        studentName: 'Verified EduLearn Graduate',
        courseTitle: 'Professional Certified Specialization',
        category: 'Information Technology & Software Engineering',
        completionDate: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
        grade: '94% (Verified Pass)',
        instructor: 'EduLearn Academic Accreditation Board',
        sha256Hash: Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join(''),
        status: 'Verified & Tamper-Proof',
        skills: ['Course Curriculum Completed', 'Hands-on Projects Passed', 'Academic Verification Approved']
      });
    }
    setSearched(true);
  };

  const selectSample = (sampleId) => {
    setCertInput(sampleId);
    setActiveCert(VERIFIED_RECORDS[sampleId]);
    setSearched(true);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="verify-page">
      <Navbar />

      <main className="verify-container">
        {/* Verification Header */}
        <section className="verify-hero animate-fade-in">
          <div className="verify-badge">
            <ShieldCheck size={18} className="text-cyan" />
            <span>EduLearn Cryptographic Credential Registry</span>
          </div>
          <h1>Public Certificate Verification Portal</h1>
          <p className="hero-subtitle">
            Validate the authenticity of academic credentials, completion transcripts, and skill badges issued by EduLearn Global.
          </p>

          {/* Search Box */}
          <form className="verify-search-form glass-panel" onSubmit={handleSearch}>
            <div className="search-input-wrap">
              <Search size={20} className="search-icon text-secondary" />
              <input 
                type="text" 
                className="verify-input" 
                placeholder="Enter Certificate ID (e.g. EDU-2026-REACT-8842)..."
                value={certInput}
                onChange={(e) => setCertInput(e.target.value)}
              />
            </div>
            <button type="submit" className="btn-verify-submit">
              Verify Credential
            </button>
          </form>

          {/* Sample quick tags */}
          <div className="sample-certs-bar">
            <span className="sample-label">Try Sample IDs:</span>
            {Object.keys(VERIFIED_RECORDS).map((sampleId) => (
              <button 
                key={sampleId} 
                className={`sample-pill ${certInput === sampleId ? 'active' : ''}`}
                onClick={() => selectSample(sampleId)}
              >
                {sampleId}
              </button>
            ))}
          </div>
        </section>

        {/* Verification Result Card */}
        {searched && activeCert && (
          <section className="cert-result-section animate-scale-up">
            <div className="cert-official-card glass-panel printable-dossier">
              {/* Top Banner */}
              <div className="cert-card-header">
                <div className="cert-auth-brand">
                  <Award size={36} className="text-amber" />
                  <div>
                    <h3>EduLearn Global Academy</h3>
                    <p className="text-secondary text-xs">Official Verification Authority • ISO 9001:2015 Accredited</p>
                  </div>
                </div>

                <div className="status-badge-verified">
                  <CheckCircle size={18} className="text-green" />
                  <span>{activeCert.status}</span>
                </div>
              </div>

              {/* Certificate Details Grid */}
              <div className="cert-details-grid">
                <div className="cert-detail-item">
                  <span className="detail-label">Recipient Name</span>
                  <h2 className="detail-value-highlight">{activeCert.studentName}</h2>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Certificate ID</span>
                  <code className="detail-code">{activeCert.id}</code>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Course Title</span>
                  <h3 className="detail-course-name">{activeCert.courseTitle}</h3>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Domain</span>
                  <span className="detail-text">{activeCert.category}</span>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Performance Grade</span>
                  <span className="detail-grade">{activeCert.grade}</span>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Issue Date</span>
                  <span className="detail-text" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    <Calendar size={15} className="text-secondary" />
                    {activeCert.completionDate}
                  </span>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Lead Instructor</span>
                  <span className="detail-text">{activeCert.instructor}</span>
                </div>

                <div className="cert-detail-item">
                  <span className="detail-label">Security Audit</span>
                  <span className="detail-text" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: '#10b981' }}>
                    <Lock size={15} /> 256-bit Cryptographic Proof
                  </span>
                </div>
              </div>

              {/* Validated Skills */}
              <div className="validated-skills-box">
                <h4>Verified Competencies & Skills Mastered</h4>
                <div className="validated-skills-list">
                  {activeCert.skills.map((s, idx) => (
                    <span key={idx} className="validated-skill-badge">
                      <CheckCircle size={13} className="text-cyan" />
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              {/* Digital Hash Seal */}
              <div className="cert-hash-seal">
                <span className="hash-label">Cryptographic Fingerprint (SHA-256):</span>
                <code className="hash-string">{activeCert.sha256Hash}</code>
              </div>

              {/* Action Buttons */}
              <div className="cert-actions-bar no-print">
                <button className="btn-outline" onClick={handlePrint}>
                  <Printer size={16} />
                  <span>Print Official Dossier</span>
                </button>
                <Link to="/courses" className="btn-primary">
                  <BookOpen size={16} />
                  <span>Explore 5,000+ Courses</span>
                </Link>
              </div>
            </div>
          </section>
        )}
      </main>
    </div>
  );
};

export default VerifyCertificate;
